In this notebook you can calculate the orientations of two crystal creating a grain boundary. This grain boundary is defined by n_go which is the normal of the grain boundary with respect to the global coordinates.
In this notebook we have:
1. `O_L`= $\Lambda_{p1}^{Go}$
2. `O_U` = $\Lambda_{p2}^{Go}$

Therefore

$\Lambda_{p2}^{Go}$ = $\Lambda_{p1}^{Go}$$\Lambda_{p2}^{p1}$

First import all packages needed.

In [1]:
import numpy as np
import numpy as np
import byxtal.bp_basis as plb
import byxtal.integer_manipulations as int_man
import byxtal.find_csl_dsc as fcd

1. `n_go`: The grain boundary normal in global ref. frame. This will be the input. 
2. `l_p_po`: $\Lambda_{p}^{po}$
3. `trans`: $\Lambda_{p2}^{p1}$

In [17]:
# Choose the gb plan normal plane you are interested in
n_go = np.array([1, 1,1])
L_p_po = 1.0 * np.array([[0.,0.5,0.5],[0.5,0.,0.5],[0.5,0.5,0.]])
# The rotation matrix corresponding to the \Sigma rotation
trans = np.array([[-1, 2, 2],[2, -1, 2],[2, 2, -1]])/3
index_type  = 'normal_g'
T_reference = 'g1'

In [18]:
# The csl calculations
L_2d_csl_p1, L_pl1_p1, L_pl2_p1 = plb.gb_2d_csl(n_go, trans, L_p_po, index_type, T_reference)

In [19]:
# a_0is parallel to the 
a_0 = L_2d_csl_p1[:,0]
a = a_0/np.linalg.norm(a_0)

b = n_go/np.linalg.norm(n_go)

c_0 = np.cross(a_0,n_go)
c = c_0/np.linalg.norm(c_0)

O_L = np.stack((a,b,c), axis=1)

O_U = np.matmul(O_L,trans)
Orient = np.zeros((3,6))
Orient[:, 0:3] = O_L
Orient[:, 3:6] = O_U
# dum the orientations to the 'orientations.txt'
np.savetxt('orientations0.txt', Orient, delimiter='\t')
print('\nThe misorientation of lower crystal')
print(O_L)
print('\nThe misorientation of upper crystal')
print(O_U)


The misorientation of lower crystal
[[ 0.          0.57735027 -0.81649658]
 [-0.70710678  0.57735027  0.40824829]
 [ 0.70710678  0.57735027  0.40824829]]

The misorientation of upper crystal
[[-0.15943087 -0.73678114  0.65706571]
 [ 0.89276797 -0.39168908 -0.2225871 ]
 [ 0.42136345  0.55111996  0.72022194]]


# Symmetrically equivalent orientation

This symmetry is for matrix (num=24):

rot = [[0,1,0][0,0,-1][-1,0,0]]

In [36]:
rot_mat = np.array([[0, 1, 0],[0, 0, -1],[-1, 0, 0]])
inv_rot_mat = np.linalg.inv(rot_mat)

In [41]:
trans_new = np.matmul(np.matmul(inv_rot_mat, trans), rot_mat)
n_go_new  = np.matmul(rot_mat, n_go)