In this notebook you can calculate the orientations of two crystal creating a grain boundary. This grain boundary is defined by n_go which is the normal of the grain boundary with respect to the global coordinates.
In this notebook we have:
1. `O_L`= $\Lambda_{p1}^{Go}$
2. `O_U` = $\Lambda_{p2}^{Go}$

Therefore

$\Lambda_{p2}^{Go}$ = $\Lambda_{p1}^{Go}$$\Lambda_{p2}^{p1}$

First import all packages needed.

In [49]:
import numpy as np
import numpy as np
import byxtal.bp_basis as plb
import byxtal.integer_manipulations as int_man
import byxtal.find_csl_dsc as fcd

1. `n_go`: The grain boundary normal in global ref. frame. This will be the input. 
2. `l_p_po`: $\Lambda_{p}^{po}$
3. `trans`: $\Lambda_{p2}^{p1}$

In [50]:
# Choose the gb plan normal plane you are interested in
n_go = np.array([0, 0,1])
L_p_po = 1.0 * np.array([[0.,0.5,0.5],[0.5,0.,0.5],[0.5,0.5,0.]])
# The rotation matrix corresponding to the \Sigma rotation
trans = np.array([[-1, 2, 2],[2, -1, 2],[2, 2, -1]])/3
index_type  = 'normal_g'
T_reference = 'g1'

In [51]:
# The csl calculations
L_2d_csl_p1, L_pl1_p1, L_pl2_p1 = plb.gb_2d_csl(n_po, t_mat, L_p_po, index_type, T_reference)

In [52]:
# a_0is parallel to the 
a_0 = L_2d_csl_p1[:,0]
a = a_0/np.linalg.norm(a_0)

b = n_po/np.linalg.norm(n_po)

c_0 = np.cross(a_0,n_po)
c = c_0/np.linalg.norm(c_0)

O_L = np.stack((a,b,c), axis=1)

O_U = np.matmul(O_L,t_mat)
Orient = np.zeros((3,6))
Orient[:, 0:3] = O_L
Orient[:, 3:6] = O_U
# dum the orientations to the 'orientations.txt'
np.savetxt('orientations.txt', Orient, delimiter='\t')
print('\nThe misorientation of lower crystal')
print(O_L)
print('\nThe misorientation of upper crystal')
print(O_U)


The misorientation of lower crystal
[[ 0.70710678  0.         -0.70710678]
 [-0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]]

The misorientation of upper crystal
[[-0.70710678  0.          0.70710678]
 [-0.23570226 -0.94280904 -0.23570226]
 [ 0.66666667 -0.33333333  0.66666667]]
